canal.instance.master.address=mysql:3306
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal123
canal.instance.connectionCharset=UTF-8
canal.instance.tsdb.enable=false

# 订阅 xplanet.article 表
canal.instance.filter.regex=xplanet\\..*
canal.instance.filter.black.regex=

canal.instance.defaultDatabaseName=xplanet
