global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'xplanet-article'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['article:8081']

  - job_name: 'xplanet-interaction'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['interaction:8082']

  - job_name: 'xplanet-user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user:8083']

  - job_name: 'xplanet-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
